# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f85806a5726d558994e50bdfd532a45a20916a32c8006cdef579cf06d9dc8ed6332f08a3238862a60518e4beaa465eaf312c905b6450ce628d44b890abd2aed

test:
  secret_key_base: 7685b81e6417957e239047bd54884ba5c122ea2f4daaa16e3d418bf2c7492baa5cd4f70ccc042806511c86fca7d24d1d359a9e9ab83c66569ede96edfb9ac46c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
